version: '3.8'

services:

  jenkins:
    build: ./jenkins
    container_name: gymnasium-jenkins-1
    ports:
      - "8080:8080"      # Portal Web do Jenkins
      - "50000:50000"    # Comunicação com Jenkins Agents (se necessário no futuro)
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Permite ao Jenkins criar containers no teu Host
    group_add:
      - "0"                                         # Garante acesso ao socket do Docker (Root/Wheel)
    restart: always

volumes:
  jenkins_data:
    name: gymnasium_jenkins_data  # Nome fixo para o volume para não perderes configurações