---
- name: Deploy Gymnasium Application
  hosts: localhost
  connection: local

  vars:
    docker_user: "joaodiofonse"
    network_name: "gym_network"

  tasks:
    - name: Garantir que a rede Docker existe
      docker_network:
        name: "{{ network_name }}"
        state: present

    - name: Levantar PostgreSQL
      docker_container:
        name: gym-db
        image: postgres:15
        state: started
        restart_policy: always
        networks:
          - name: "{{ network_name }}"
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "12345"
          POSTGRES_DB: "gymnasium"
        volumes:
          - gym_db_data:/var/lib/postgresql/data

    - name: Levantar Backend
      docker_container:
        name: gym-backend
        image: "{{ docker_user }}/gymnasium-backend:latest"
        state: started
        pull: true
        restart_policy: always
        networks:
          - name: "{{ network_name }}"
        ports:
          - "8000:8000"
        env:
          DATABASE_URL: "postgresql://postgres:12345@gym-db:5432/gymnasium"

    - name: Levantar Frontend
      docker_container:
        name: gym-frontend
        image: "{{ docker_user }}/gymnasium-frontend:latest"
        state: started
        pull: true
        restart_policy: always
        networks:
          - name: "{{ network_name }}"
        ports:
          - "3000:80"