---
- name: Deploy Gymnasium Application (3-Tier Architecture)
  hosts: localhost
  connection: local
  become: no  # Necessário para gerir o Docker socket

  vars:
    docker_user: "sobreiraa12344"
    network_name: "gym_network"

  tasks:
    - name: 1. Garantir que a rede Docker existe
      docker_network:
        name: "{{ network_name }}"
        state: present

    - name: 2. Camada de Dados - Levantar Postgres (Imagem Oficial)
      docker_container:
        name: gym-db
        image: postgres:latest
        state: started
        restart_policy: always
        networks:
          - name: "{{ network_name }}"
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "janeiro2004"
          POSTGRES_DB: "GymApp"
        # Garante a persistência dos dados exigida na ficha
        volumes:
          - gym_db_data:/var/lib/postgresql/data

    - name: 3. Camada Backend - Gymnasium API
      docker_container:
        name: gym-backend
        image: "{{ docker_user }}/gym-backend:latest"
        state: started
        pull: true  # Requisito de Upgrade: Puxa sempre a versão mais recente do Hub
        restart_policy: always
        networks:
          - name: "{{ network_name }}"
        ports:
          - "8000:8000"
        env:
          # Usando o nome do container "gym-db" para comunicação na rede interna
          DATABASE_URL: "postgresql://postgres:janeiro2004@gym-db:5432/GymApp"

    - name: 4. Camada Frontend - Website
      docker_container:
        name: gym-frontend
        image: "{{ docker_user }}/gym-frontend:latest"
        state: started
        pull: true
        restart_policy: always
        networks:
          - name: "{{ network_name }}"
        ports:
          # Alterado para 3001 (antes era 3000)para resolver de vez o conflito de portas do teu sistema
          - "3001:80"

    - name: 5. Limpar imagens antigas (Opcional - poupa espaço)
      docker_prune:
        images: yes
        images_filters:
          dangling: false